[package]
name = "tsne_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "tsne_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bhtsne = "0.5.1"
rustler = "0.27.0"
